source run_jobs.sh 00 &
source run_jobs.sh 01 &
source run_jobs.sh 02 &
source run_jobs.sh 03 &
source run_jobs.sh 04 &
source run_jobs.sh 05 &
source run_jobs.sh 06 &
source run_jobs.sh 07 &
source run_jobs.sh 08 &
source run_jobs.sh 09 &
source run_jobs.sh 10 &
source run_jobs.sh 11 &
source run_jobs.sh 12 &
source run_jobs.sh 13 &
source run_jobs.sh 14 &
source run_jobs.sh 15 &
source run_jobs.sh 16 &
source run_jobs.sh 17 &
source run_jobs.sh 18 &
source run_jobs.sh 19 &
