source run_jobs.sh 00 &
source run_jobs.sh 01 &
source run_jobs.sh 02 &
source run_jobs.sh 03 &
source run_jobs.sh 04 &
source run_jobs.sh 05 &
source run_jobs.sh 06 &
source run_jobs.sh 07 &
source run_jobs.sh 08 &
source run_jobs.sh 09 &
